title: My awesome first Github Pages
author: Emad Abd Elhamid
email: emadabel@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  This is emad's github page from github traning lab tutorial.

# social links
twitter_username: emadabel
github_username:  emadabel

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
